// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iprggvzctrkdeleodlpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwcmdndnpjdHJrZGVsZW9kbHB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDE3NTcsImV4cCI6MjA1OTUxNzc1N30.Qpo6dsjXOTHsBYTBj8b_LdgyCjn5SX_KXXzY4Yq33Qo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);